version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT:-5001}:5001"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/trezorerie.db:/app/trezorerie.db
    restart: always

  frontend:
    build: .
    ports:
      - "${FRONTEND_PORT:-3005}:80"
    restart: always